// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJWV3881mX5Fx3seTmeMPpjLCcYri9vZA',
    appId: '1:237170196166:web:73626037fcdff93b0461c7',
    messagingSenderId: '237170196166',
    projectId: 'chat-53eab',
    authDomain: 'chat-53eab.firebaseapp.com',
    storageBucket: 'chat-53eab.appspot.com',
    measurementId: 'G-EZWT9N661W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoSsIAyc6sFqLzsgXVZEBi-k8HOF50Ok',
    appId: '1:237170196166:android:bd4c2b5634c34a900461c7',
    messagingSenderId: '237170196166',
    projectId: 'chat-53eab',
    storageBucket: 'chat-53eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5FT3hpAqzJATwS1Kj0q76tRENNQUiWY',
    appId: '1:237170196166:ios:00da4dd47d79f11a0461c7',
    messagingSenderId: '237170196166',
    projectId: 'chat-53eab',
    storageBucket: 'chat-53eab.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5FT3hpAqzJATwS1Kj0q76tRENNQUiWY',
    appId: '1:237170196166:ios:00da4dd47d79f11a0461c7',
    messagingSenderId: '237170196166',
    projectId: 'chat-53eab',
    storageBucket: 'chat-53eab.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJWV3881mX5Fx3seTmeMPpjLCcYri9vZA',
    appId: '1:237170196166:web:c048d81b4bd38fde0461c7',
    messagingSenderId: '237170196166',
    projectId: 'chat-53eab',
    authDomain: 'chat-53eab.firebaseapp.com',
    storageBucket: 'chat-53eab.appspot.com',
    measurementId: 'G-Q8DR84SX84',
  );
}
